# Generated by Django 3.2 on 2022-03-08 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantAPP', '0002_auto_20220308_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='restaurant',
        ),
    ]
